### ISSUE TITLE
Service extension

### ISSUE THREAD

**Issue by utybo** [utybo/Shedinja#5]
### Goal

Provide a way to automatically start and programmatically stop a set of specific components within a Shedinja application, without requiring manually going through a list of components and manually starting them.

### Use cases

- I want to use Shedinja in an app that connects to a DB and to some client X. I need to call some `.connect()` or `.start()` function on those services in order to use them. I would like Shedinja to do this automatically for me.
    - I want the start/stop functions to be compatible with coroutines
    - I want the starting and stopping processes to be done in parallel to optimize startup time, unless I explicitly disable it
    - I want the starting and stopping processes to give me statistics on how much time was taken.
    - I want the application to safely stop when startup fails.

#### Workaround

Manually start and stop these services by retrieving them with the existing `get()` methods.

### API/DSL

```kotlin
// Starts in a non-suspending way
class Database(scope: InjectionScope) : StartableService {
    private val dbConfiguration by scope()
    private lateinit var connection: DatabaseConnection

    fun start() {
        connection = DatabaseConnection(dbConfiguration)
        connection.connect()
    }
}

// Starts and stops in a suspending way
class ChatClient(scope: InjectionScope) : SuspendingStoppableService {
    private val chatConfiguration by scope()
    private lateinit var connection: ChatConnection

    suspend fun start() {
        connection = ChatConnection(chatConfiguration)
        connection.connect()
    }

    suspend fun stop() {
        connection.disconnect()
    }
}

val env = shedinja {
    useServices()
    put(::Database)
    put(::ChatClient)
    // ...
}

env.services.startAll()
```

### Limitations

`¯\_(ツ)_/¯`

### TODO

- [X] Create a proper extension/plugin system onto environments. Unlike factories, this feature requires proper state storage and additional capabilities that are not provided by the base InjectionEnvironment interface.
    - Possibilities: 
        - `ExtensibleInjectionEnvironment` interface + `AbstractExtensibleInjectionEnvironment` with default implementations for the interface. Would provide a "meta-environment" for the extensions.
        - ~~Something else?~~
- [X] ~~Provide 4 interfaces: StartableService, SuspendingStartableService, StoppableService, SuspendingStoppableService.~~ Simplified: only provide `ShedinjaService` and `SuspendShedinjaService`.
- [X] Provide a way to start and stop all services directly via the environment.
- [x] Provide statistics on time services took to start
- [X] ~~Provide a check that verifies that components do not implement both the suspend and non-suspend functions. This would otherwise lead to double-starting and double-stopping, which is probably not intended.~~ Coincidentally, this will just throw a compile error, as signatures are identical except for the "suspendness" of ShedinjaService vs SuspsendShedinjaService
